--------------------------------------------------------
--  File created - Çarþamba-Ocak-03-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence AUTHORCOUNT
--------------------------------------------------------

   CREATE SEQUENCE  "B21427291"."AUTHORCOUNT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence CARICATURISTCOUNT
--------------------------------------------------------

   CREATE SEQUENCE  "B21427291"."CARICATURISTCOUNT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence ITEMCOUNT
--------------------------------------------------------

   CREATE SEQUENCE  "B21427291"."ITEMCOUNT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence PHOTOGRAPHERCOUNT
--------------------------------------------------------

   CREATE SEQUENCE  "B21427291"."PHOTOGRAPHERCOUNT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence PUBLISHERCOUNT
--------------------------------------------------------

   CREATE SEQUENCE  "B21427291"."PUBLISHERCOUNT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence UPLOADERCOUNT
--------------------------------------------------------

   CREATE SEQUENCE  "B21427291"."UPLOADERCOUNT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence UPLOADITEMCOUNT
--------------------------------------------------------

   CREATE SEQUENCE  "B21427291"."UPLOADITEMCOUNT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Table ADD_SUBJECT_BOOK
--------------------------------------------------------

  CREATE TABLE "B21427291"."ADD_SUBJECT_BOOK" 
   (	"ADMINEMAIL" VARCHAR2(30 BYTE), 
	"ITEMID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ADD_SUBJECT_CARICATURE
--------------------------------------------------------

  CREATE TABLE "B21427291"."ADD_SUBJECT_CARICATURE" 
   (	"ADMINEMAIL" VARCHAR2(30 BYTE), 
	"ITEMID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ADD_SUBJECT_WALLPAPER
--------------------------------------------------------

  CREATE TABLE "B21427291"."ADD_SUBJECT_WALLPAPER" 
   (	"ADMINEMAIL" VARCHAR2(30 BYTE), 
	"ITEMID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "B21427291"."ADMIN" 
   (	"TC" VARCHAR2(11 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"SURNAME" VARCHAR2(20 BYTE), 
	"PHONENUMBER" VARCHAR2(10 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"ADDRESS" VARCHAR2(60 BYTE), 
	"MEMBERSHIPDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ADMIN1
--------------------------------------------------------

  CREATE TABLE "B21427291"."ADMIN1" 
   (	"EMAIL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ADMIN2
--------------------------------------------------------

  CREATE TABLE "B21427291"."ADMIN2" 
   (	"EMAIL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUTHOR
--------------------------------------------------------

  CREATE TABLE "B21427291"."AUTHOR" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"ITEMID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BOOK
--------------------------------------------------------

  CREATE TABLE "B21427291"."BOOK" 
   (	"NUMBEROFPAGES" NUMBER(5,0), 
	"LANGUAGE" VARCHAR2(30 BYTE), 
	"ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CARICATURE
--------------------------------------------------------

  CREATE TABLE "B21427291"."CARICATURE" 
   (	"ID" NUMBER(*,0), 
	"LANGUAGE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CARICATURIST
--------------------------------------------------------

  CREATE TABLE "B21427291"."CARICATURIST" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"ITEMID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DOWNLOADHISTORY
--------------------------------------------------------

  CREATE TABLE "B21427291"."DOWNLOADHISTORY" 
   (	"USEREMAIL" VARCHAR2(30 BYTE), 
	"ITEMID" NUMBER(*,0), 
	"DOWNLOADDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DOWNLOADITEMADMIN
--------------------------------------------------------

  CREATE TABLE "B21427291"."DOWNLOADITEMADMIN" 
   (	"ADMINEMAIL" VARCHAR2(30 BYTE), 
	"ITEMID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DOWNLOADITEMUSER
--------------------------------------------------------

  CREATE TABLE "B21427291"."DOWNLOADITEMUSER" 
   (	"USEREMAIL" VARCHAR2(30 BYTE), 
	"ITEMID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ITEM
--------------------------------------------------------

  CREATE TABLE "B21427291"."ITEM" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"RELEASEYEAR" NUMBER(*,0), 
	"UPLOADDATE" DATE, 
	"SUBJECT" VARCHAR2(30 BYTE), 
	"DIRECTORY" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PHOTOGRAPHER
--------------------------------------------------------

  CREATE TABLE "B21427291"."PHOTOGRAPHER" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"ITEMID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PUBLISHER
--------------------------------------------------------

  CREATE TABLE "B21427291"."PUBLISHER" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"ITEMID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUPERUSERREQUEST
--------------------------------------------------------

  CREATE TABLE "B21427291"."SUPERUSERREQUEST" 
   (	"EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table UKEEP
--------------------------------------------------------

  CREATE TABLE "B21427291"."UKEEP" 
   (	"USEREMAIL" VARCHAR2(30 BYTE), 
	"UPLOADID" NUMBER(*,0), 
	"REQUESTDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table UPLOAD_BOOK
--------------------------------------------------------

  CREATE TABLE "B21427291"."UPLOAD_BOOK" 
   (	"NUMBEROFPAGES" NUMBER(*,0), 
	"PUBLISHERNAME" VARCHAR2(30 BYTE), 
	"PUBLISHEREMAIL" VARCHAR2(40 BYTE), 
	"AUTHORNAME" VARCHAR2(30 BYTE), 
	"AUTHOREMAIL" VARCHAR2(40 BYTE), 
	"LANGUAGE" VARCHAR2(20 BYTE), 
	"UPLOADID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table UPLOAD_CARICATURE
--------------------------------------------------------

  CREATE TABLE "B21427291"."UPLOAD_CARICATURE" 
   (	"UPLOADERNAME" VARCHAR2(30 BYTE), 
	"UPLOADEREMAIL" VARCHAR2(40 BYTE), 
	"CARICATURISTNAME" VARCHAR2(30 BYTE), 
	"CARICATURISTEMAIL" VARCHAR2(40 BYTE), 
	"LANGUAGE" VARCHAR2(20 BYTE), 
	"UPLOADID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table UPLOADER
--------------------------------------------------------

  CREATE TABLE "B21427291"."UPLOADER" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"ITEMID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table UPLOAD_ITEM
--------------------------------------------------------

  CREATE TABLE "B21427291"."UPLOAD_ITEM" 
   (	"USEREMAIL" VARCHAR2(30 BYTE), 
	"UPLOADID" NUMBER(*,0), 
	"SUBJECT" VARCHAR2(30 BYTE), 
	"UPLOADDATE" DATE, 
	"NAME" VARCHAR2(30 BYTE), 
	"RELEASEYEAR" NUMBER(*,0), 
	"ITEMDIRECTORY" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table UPLOAD_WALLPAPER
--------------------------------------------------------

  CREATE TABLE "B21427291"."UPLOAD_WALLPAPER" 
   (	"PHOTOGRAPHERNAME" VARCHAR2(30 BYTE), 
	"PHOTOGRAPHEREMAIL" VARCHAR2(40 BYTE), 
	"UPLOADID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "B21427291"."USERS" 
   (	"TC" VARCHAR2(11 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"SURNAME" VARCHAR2(20 BYTE), 
	"PHONENUMBER" VARCHAR2(10 BYTE), 
	"ADDRESS" VARCHAR2(60 BYTE), 
	"MEMBERSHIPDATE" DATE, 
	"EMAIL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER1
--------------------------------------------------------

  CREATE TABLE "B21427291"."USER1" 
   (	"EMAIL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER2
--------------------------------------------------------

  CREATE TABLE "B21427291"."USER2" 
   (	"SUPERMEMBERSHIPDATE" DATE, 
	"EMAIL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table WALLPAPER
--------------------------------------------------------

  CREATE TABLE "B21427291"."WALLPAPER" 
   (	"ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into B21427291.ADD_SUBJECT_BOOK
SET DEFINE OFF;
REM INSERTING into B21427291.ADD_SUBJECT_CARICATURE
SET DEFINE OFF;
REM INSERTING into B21427291.ADD_SUBJECT_WALLPAPER
SET DEFINE OFF;
REM INSERTING into B21427291.ADMIN
SET DEFINE OFF;
Insert into B21427291.ADMIN (TC,PASSWORD,NAME,SURNAME,PHONENUMBER,EMAIL,ADDRESS,MEMBERSHIPDATE) values ('111','testpas','admin1','surname','05435278','admin1@hotmail.com','adminadress',to_date('18/12/2017','DD/MM/RRRR'));
Insert into B21427291.ADMIN (TC,PASSWORD,NAME,SURNAME,PHONENUMBER,EMAIL,ADDRESS,MEMBERSHIPDATE) values ('1234567891','pass','veli','deli','053222','admin2@hotmail.com','address',to_date('19/12/2017','DD/MM/RRRR'));
REM INSERTING into B21427291.ADMIN1
SET DEFINE OFF;
Insert into B21427291.ADMIN1 (EMAIL) values ('admin1@hotmail.com');
REM INSERTING into B21427291.ADMIN2
SET DEFINE OFF;
Insert into B21427291.ADMIN2 (EMAIL) values ('admin2@hotmail.com');
REM INSERTING into B21427291.AUTHOR
SET DEFINE OFF;
Insert into B21427291.AUTHOR (ID,NAME,EMAIL,ITEMID) values ('45','pub','publi','73');
Insert into B21427291.AUTHOR (ID,NAME,EMAIL,ITEMID) values ('46','pub','publi','74');
Insert into B21427291.AUTHOR (ID,NAME,EMAIL,ITEMID) values ('53','tt','t@hotma','81');
Insert into B21427291.AUTHOR (ID,NAME,EMAIL,ITEMID) values ('50','a','a','78');
Insert into B21427291.AUTHOR (ID,NAME,EMAIL,ITEMID) values ('51','a','a','79');
Insert into B21427291.AUTHOR (ID,NAME,EMAIL,ITEMID) values ('52','a','a','80');
Insert into B21427291.AUTHOR (ID,NAME,EMAIL,ITEMID) values ('44','pub','publi','72');
Insert into B21427291.AUTHOR (ID,NAME,EMAIL,ITEMID) values ('47','pub','publi','75');
Insert into B21427291.AUTHOR (ID,NAME,EMAIL,ITEMID) values ('48','pub','publi','76');
Insert into B21427291.AUTHOR (ID,NAME,EMAIL,ITEMID) values ('49','pub','p','77');
REM INSERTING into B21427291.BOOK
SET DEFINE OFF;
Insert into B21427291.BOOK (NUMBEROFPAGES,LANGUAGE,ID) values ('102','deutsch','73');
Insert into B21427291.BOOK (NUMBEROFPAGES,LANGUAGE,ID) values ('103','English','74');
Insert into B21427291.BOOK (NUMBEROFPAGES,LANGUAGE,ID) values ('1000','English','81');
Insert into B21427291.BOOK (NUMBEROFPAGES,LANGUAGE,ID) values ('123','deutsch','78');
Insert into B21427291.BOOK (NUMBEROFPAGES,LANGUAGE,ID) values ('123','deutsch','79');
Insert into B21427291.BOOK (NUMBEROFPAGES,LANGUAGE,ID) values ('123','deutsch','80');
Insert into B21427291.BOOK (NUMBEROFPAGES,LANGUAGE,ID) values ('102','italian','72');
Insert into B21427291.BOOK (NUMBEROFPAGES,LANGUAGE,ID) values ('105','English','75');
Insert into B21427291.BOOK (NUMBEROFPAGES,LANGUAGE,ID) values ('100','french','76');
Insert into B21427291.BOOK (NUMBEROFPAGES,LANGUAGE,ID) values ('106','french','77');
REM INSERTING into B21427291.CARICATURE
SET DEFINE OFF;
Insert into B21427291.CARICATURE (ID,LANGUAGE) values ('60','english');
Insert into B21427291.CARICATURE (ID,LANGUAGE) values ('61','english');
Insert into B21427291.CARICATURE (ID,LANGUAGE) values ('62','english');
Insert into B21427291.CARICATURE (ID,LANGUAGE) values ('63','english');
Insert into B21427291.CARICATURE (ID,LANGUAGE) values ('64','english');
Insert into B21427291.CARICATURE (ID,LANGUAGE) values ('65','english');
Insert into B21427291.CARICATURE (ID,LANGUAGE) values ('66','english');
Insert into B21427291.CARICATURE (ID,LANGUAGE) values ('67','english');
Insert into B21427291.CARICATURE (ID,LANGUAGE) values ('68','english');
Insert into B21427291.CARICATURE (ID,LANGUAGE) values ('69','english');
REM INSERTING into B21427291.CARICATURIST
SET DEFINE OFF;
Insert into B21427291.CARICATURIST (ID,NAME,EMAIL,ITEMID) values ('23','caricaturist1','caricaturist@info.me','60');
Insert into B21427291.CARICATURIST (ID,NAME,EMAIL,ITEMID) values ('24','caricaturist1','caricaturist@info.me','61');
Insert into B21427291.CARICATURIST (ID,NAME,EMAIL,ITEMID) values ('25','caricaturist1','caricaturist@info.me','62');
Insert into B21427291.CARICATURIST (ID,NAME,EMAIL,ITEMID) values ('26','caricaturist1','caricaturist@info.me','63');
Insert into B21427291.CARICATURIST (ID,NAME,EMAIL,ITEMID) values ('27','caricaturist1','caricaturist@info.me','64');
Insert into B21427291.CARICATURIST (ID,NAME,EMAIL,ITEMID) values ('28','caricaturist1','caricaturist@info.me','65');
Insert into B21427291.CARICATURIST (ID,NAME,EMAIL,ITEMID) values ('29','caricaturist1','caricaturist@info.me','66');
Insert into B21427291.CARICATURIST (ID,NAME,EMAIL,ITEMID) values ('30','caricaturist1','caricaturist@info.me','67');
Insert into B21427291.CARICATURIST (ID,NAME,EMAIL,ITEMID) values ('31','caricaturist1','caricaturist@info.me','68');
Insert into B21427291.CARICATURIST (ID,NAME,EMAIL,ITEMID) values ('32','caricaturist1','caricaturist@info.me','69');
REM INSERTING into B21427291.DOWNLOADHISTORY
SET DEFINE OFF;
Insert into B21427291.DOWNLOADHISTORY (USEREMAIL,ITEMID,DOWNLOADDATE) values ('test@hotmail.com','78',to_date('04/01/2018','DD/MM/RRRR'));
Insert into B21427291.DOWNLOADHISTORY (USEREMAIL,ITEMID,DOWNLOADDATE) values ('test2@hotmail.com','62',to_date('03/01/2018','DD/MM/RRRR'));
Insert into B21427291.DOWNLOADHISTORY (USEREMAIL,ITEMID,DOWNLOADDATE) values ('test@hotmail.com','81',to_date('04/01/2018','DD/MM/RRRR'));
Insert into B21427291.DOWNLOADHISTORY (USEREMAIL,ITEMID,DOWNLOADDATE) values ('test2@hotmail.com','78',to_date('04/01/2018','DD/MM/RRRR'));
Insert into B21427291.DOWNLOADHISTORY (USEREMAIL,ITEMID,DOWNLOADDATE) values ('test2@hotmail.com','51',to_date('04/01/2018','DD/MM/RRRR'));
Insert into B21427291.DOWNLOADHISTORY (USEREMAIL,ITEMID,DOWNLOADDATE) values ('test@hotmail.com','63',to_date('03/01/2018','DD/MM/RRRR'));
Insert into B21427291.DOWNLOADHISTORY (USEREMAIL,ITEMID,DOWNLOADDATE) values ('test@hotmail.com','73',to_date('03/01/2018','DD/MM/RRRR'));
Insert into B21427291.DOWNLOADHISTORY (USEREMAIL,ITEMID,DOWNLOADDATE) values ('test@hotmail.com','62',to_date('03/01/2018','DD/MM/RRRR'));
Insert into B21427291.DOWNLOADHISTORY (USEREMAIL,ITEMID,DOWNLOADDATE) values ('test@gmail.com','78',to_date('03/01/2018','DD/MM/RRRR'));
Insert into B21427291.DOWNLOADHISTORY (USEREMAIL,ITEMID,DOWNLOADDATE) values ('test@hotmail.com','69',to_date('03/01/2018','DD/MM/RRRR'));
Insert into B21427291.DOWNLOADHISTORY (USEREMAIL,ITEMID,DOWNLOADDATE) values ('test@gmail.com','63',to_date('03/01/2018','DD/MM/RRRR'));
Insert into B21427291.DOWNLOADHISTORY (USEREMAIL,ITEMID,DOWNLOADDATE) values ('test@gmail.com','51',to_date('03/01/2018','DD/MM/RRRR'));
Insert into B21427291.DOWNLOADHISTORY (USEREMAIL,ITEMID,DOWNLOADDATE) values ('test2@hotmail.com','63',to_date('04/01/2018','DD/MM/RRRR'));
REM INSERTING into B21427291.DOWNLOADITEMADMIN
SET DEFINE OFF;
REM INSERTING into B21427291.DOWNLOADITEMUSER
SET DEFINE OFF;
REM INSERTING into B21427291.ITEM
SET DEFINE OFF;
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('60','cari1','2018',to_date('03/01/2018','DD/MM/RRRR'),'fun','uploadcaricature/cae1696750ca5b6fa4f1da0ffc708dfd.jpg');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('61','cari2','2018',to_date('03/01/2018','DD/MM/RRRR'),'fun','uploadcaricature/d8fc7d08789efda5ecc460c04bf8e6ae--political-cartoons-the-medium.jpg');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('62','cari3','2018',to_date('03/01/2018','DD/MM/RRRR'),'fun','uploadcaricature/download.jpeg');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('63','cari4','2018',to_date('03/01/2018','DD/MM/RRRR'),'fun','uploadcaricature/download (2).jpeg');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('64','cari5','2018',to_date('03/01/2018','DD/MM/RRRR'),'fun','uploadcaricature/images.jpeg');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('65','cari6','2018',to_date('03/01/2018','DD/MM/RRRR'),'fun','uploadcaricature/images.png');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('66','cari7','2018',to_date('03/01/2018','DD/MM/RRRR'),'fun','uploadcaricature/images (1).jpeg');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('67','cari8','2018',to_date('03/01/2018','DD/MM/RRRR'),'fun','uploadcaricature/images (3).jpeg');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('68','cari9','2018',to_date('03/01/2018','DD/MM/RRRR'),'fun','uploadcaricature/images (2).jpeg');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('69','cari10','2018',to_date('03/01/2018','DD/MM/RRRR'),'fun','uploadcaricature/images (4).jpeg');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('73','Ron','1990',to_date('03/01/2018','DD/MM/RRRR'),'adventure','uploadbook/BlockCiphers_4.pdf');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('74','Malfoy','1990',to_date('03/01/2018','DD/MM/RRRR'),'Terror','uploadbook/DigitalCert_4.pdf');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('81','Call Wild','1980',to_date('03/01/2018','DD/MM/RRRR'),'Horror','uploadbook/midterm_key (1).pdf');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('72','Hermonie','1989',to_date('03/01/2018','DD/MM/RRRR'),'Horror','uploadbook/BasicCiphers_4.pdf');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('79','Ask to People','1996',to_date('03/01/2018','DD/MM/RRRR'),'Horror','uploadbook/OSSec_4.pdf');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('80','The Life','2000',to_date('03/01/2018','DD/MM/RRRR'),'adventure','uploadbook/Threshold_4.pdf');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('78','David','1996',to_date('03/01/2018','DD/MM/RRRR'),'Love','uploadbook/SecurityHandshake_4.pdf');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('50','wall1','2018',to_date('03/01/2018','DD/MM/RRRR'),'nature','uploadwallpaper/download.jpeg');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('51','wall2','2018',to_date('03/01/2018','DD/MM/RRRR'),'nature','uploadwallpaper/download (1).jpeg');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('52','wall3','2018',to_date('03/01/2018','DD/MM/RRRR'),'nature','uploadwallpaper/images.jpeg');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('53','wall4','2018',to_date('03/01/2018','DD/MM/RRRR'),'nature','uploadwallpaper/images (1).jpeg');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('54','wall5','2018',to_date('03/01/2018','DD/MM/RRRR'),'nature','uploadwallpaper/images (2).jpeg');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('55','wall6','2018',to_date('03/01/2018','DD/MM/RRRR'),'nature','uploadwallpaper/images (3).jpeg');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('56','wall7','2018',to_date('03/01/2018','DD/MM/RRRR'),'nature','uploadwallpaper/images (4).jpeg');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('57','wall8','2018',to_date('03/01/2018','DD/MM/RRRR'),'nature','uploadwallpaper/images (5).jpeg');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('58','wall9','2018',to_date('03/01/2018','DD/MM/RRRR'),'nature','uploadwallpaper/images (6).jpeg');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('59','wall10','2018',to_date('03/01/2018','DD/MM/RRRR'),'nature','uploadwallpaper/images (7).jpeg');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('75','Snape','1991',to_date('03/01/2018','DD/MM/RRRR'),'Love','uploadbook/HashFunctions_4.pdf');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('76','Harry','1988',to_date('03/01/2018','DD/MM/RRRR'),'Fiction','uploadbook/Authentication_4.pdf');
Insert into B21427291.ITEM (ID,NAME,RELEASEYEAR,UPLOADDATE,SUBJECT,DIRECTORY) values ('77','Drago','1995',to_date('03/01/2018','DD/MM/RRRR'),'Fiction','uploadbook/Malware_4.pdf');
REM INSERTING into B21427291.PHOTOGRAPHER
SET DEFINE OFF;
Insert into B21427291.PHOTOGRAPHER (ID,NAME,EMAIL,ITEMID) values ('42','photographer1','pho@foti.com','50');
Insert into B21427291.PHOTOGRAPHER (ID,NAME,EMAIL,ITEMID) values ('43','photographer2','pho@foti.com','51');
Insert into B21427291.PHOTOGRAPHER (ID,NAME,EMAIL,ITEMID) values ('44','photographer3','pho@foti.com','52');
Insert into B21427291.PHOTOGRAPHER (ID,NAME,EMAIL,ITEMID) values ('45','photographer4','pho@foti.com','53');
Insert into B21427291.PHOTOGRAPHER (ID,NAME,EMAIL,ITEMID) values ('46','photographer5','pho@foti.com','54');
Insert into B21427291.PHOTOGRAPHER (ID,NAME,EMAIL,ITEMID) values ('47','photographer6','pho@foti.com','55');
Insert into B21427291.PHOTOGRAPHER (ID,NAME,EMAIL,ITEMID) values ('48','photographer7','pho@foti.com','56');
Insert into B21427291.PHOTOGRAPHER (ID,NAME,EMAIL,ITEMID) values ('49','photographer8','pho@foti.com','57');
Insert into B21427291.PHOTOGRAPHER (ID,NAME,EMAIL,ITEMID) values ('50','photographer9','pho@foti.com','58');
Insert into B21427291.PHOTOGRAPHER (ID,NAME,EMAIL,ITEMID) values ('51','photographer10','pho@foti.com','59');
REM INSERTING into B21427291.PUBLISHER
SET DEFINE OFF;
Insert into B21427291.PUBLISHER (ID,NAME,EMAIL,ITEMID) values ('45','alen@alen.com','hans','73');
Insert into B21427291.PUBLISHER (ID,NAME,EMAIL,ITEMID) values ('46','alen@alen.com','nick','74');
Insert into B21427291.PUBLISHER (ID,NAME,EMAIL,ITEMID) values ('53','f@hotmail','j.k rowling','81');
Insert into B21427291.PUBLISHER (ID,NAME,EMAIL,ITEMID) values ('50','alen@alen.com','alen','78');
Insert into B21427291.PUBLISHER (ID,NAME,EMAIL,ITEMID) values ('51','alen@alen.com','alen','79');
Insert into B21427291.PUBLISHER (ID,NAME,EMAIL,ITEMID) values ('52','alen@alen.com','alen','80');
Insert into B21427291.PUBLISHER (ID,NAME,EMAIL,ITEMID) values ('44','vero@ver.com','veronica','72');
Insert into B21427291.PUBLISHER (ID,NAME,EMAIL,ITEMID) values ('47','alen@alen.com','alen','75');
Insert into B21427291.PUBLISHER (ID,NAME,EMAIL,ITEMID) values ('48','alen@alen.com','alen','76');
Insert into B21427291.PUBLISHER (ID,NAME,EMAIL,ITEMID) values ('49','alen@alen.com','alen','77');
REM INSERTING into B21427291.SUPERUSERREQUEST
SET DEFINE OFF;
Insert into B21427291.SUPERUSERREQUEST (EMAIL) values ('admin1@hotmail.com');
REM INSERTING into B21427291.UKEEP
SET DEFINE OFF;
REM INSERTING into B21427291.UPLOAD_BOOK
SET DEFINE OFF;
REM INSERTING into B21427291.UPLOAD_CARICATURE
SET DEFINE OFF;
REM INSERTING into B21427291.UPLOADER
SET DEFINE OFF;
Insert into B21427291.UPLOADER (ID,NAME,EMAIL,ITEMID) values ('23','anonymous1','anonym@anonim.me','60');
Insert into B21427291.UPLOADER (ID,NAME,EMAIL,ITEMID) values ('24','anonymous2','anonym@anonim.me','61');
Insert into B21427291.UPLOADER (ID,NAME,EMAIL,ITEMID) values ('25','anonymous1','anonym@anonim.me','62');
Insert into B21427291.UPLOADER (ID,NAME,EMAIL,ITEMID) values ('26','anonymous1','anonym@anonim.me','63');
Insert into B21427291.UPLOADER (ID,NAME,EMAIL,ITEMID) values ('27','anonymous1','anonym@anonim.me','64');
Insert into B21427291.UPLOADER (ID,NAME,EMAIL,ITEMID) values ('28','anonymous1','anonym@anonim.me','65');
Insert into B21427291.UPLOADER (ID,NAME,EMAIL,ITEMID) values ('29','anonymous1','anonym@anonim.me','66');
Insert into B21427291.UPLOADER (ID,NAME,EMAIL,ITEMID) values ('30','anonymous1','anonym@anonim.me','67');
Insert into B21427291.UPLOADER (ID,NAME,EMAIL,ITEMID) values ('31','anonymous1','anonym@anonim.me','68');
Insert into B21427291.UPLOADER (ID,NAME,EMAIL,ITEMID) values ('32','anonymous1','anonym@anonim.me','69');
REM INSERTING into B21427291.UPLOAD_ITEM
SET DEFINE OFF;
REM INSERTING into B21427291.UPLOAD_WALLPAPER
SET DEFINE OFF;
REM INSERTING into B21427291.USERS
SET DEFINE OFF;
Insert into B21427291.USERS (TC,PASSWORD,NAME,SURNAME,PHONENUMBER,ADDRESS,MEMBERSHIPDATE,EMAIL) values ('123','4124bc0a9335c27f086f24ba207a4912','test','ee','034234432','dd',to_date('03/01/2018','DD/MM/RRRR'),'test3@hotmail.com');
Insert into B21427291.USERS (TC,PASSWORD,NAME,SURNAME,PHONENUMBER,ADDRESS,MEMBERSHIPDATE,EMAIL) values ('32423342','202cb962ac59075b964b07152d234b70','test','testsur','032344232','adress',to_date('03/01/2018','DD/MM/RRRR'),'test@hotmail.com');
Insert into B21427291.USERS (TC,PASSWORD,NAME,SURNAME,PHONENUMBER,ADDRESS,MEMBERSHIPDATE,EMAIL) values ('3332324','caf1a3dfb505ffed0d024130f58c5cfa','dd','dd','4355423','dd',to_date('03/01/2018','DD/MM/RRRR'),'test2@hotmail.com');
Insert into B21427291.USERS (TC,PASSWORD,NAME,SURNAME,PHONENUMBER,ADDRESS,MEMBERSHIPDATE,EMAIL) values ('32243343434','202cb962ac59075b964b07152d234b70','ahmet','mutlu','05324323','Universiteler mah. cankaya',to_date('03/01/2018','DD/MM/RRRR'),'test@gmail.com');
REM INSERTING into B21427291.USER1
SET DEFINE OFF;
Insert into B21427291.USER1 (EMAIL) values ('test3@hotmail.com');
REM INSERTING into B21427291.USER2
SET DEFINE OFF;
Insert into B21427291.USER2 (SUPERMEMBERSHIPDATE,EMAIL) values (to_date('03/01/2018','DD/MM/RRRR'),'test@hotmail.com');
Insert into B21427291.USER2 (SUPERMEMBERSHIPDATE,EMAIL) values (to_date('03/01/2018','DD/MM/RRRR'),'test@gmail.com');
Insert into B21427291.USER2 (SUPERMEMBERSHIPDATE,EMAIL) values (to_date('03/01/2018','DD/MM/RRRR'),'test2@hotmail.com');
REM INSERTING into B21427291.WALLPAPER
SET DEFINE OFF;
Insert into B21427291.WALLPAPER (ID) values ('50');
Insert into B21427291.WALLPAPER (ID) values ('51');
Insert into B21427291.WALLPAPER (ID) values ('52');
Insert into B21427291.WALLPAPER (ID) values ('53');
Insert into B21427291.WALLPAPER (ID) values ('54');
Insert into B21427291.WALLPAPER (ID) values ('55');
Insert into B21427291.WALLPAPER (ID) values ('56');
Insert into B21427291.WALLPAPER (ID) values ('57');
Insert into B21427291.WALLPAPER (ID) values ('58');
Insert into B21427291.WALLPAPER (ID) values ('59');
--------------------------------------------------------
--  DDL for Trigger AUTHOR_AUTOINCREMENT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "B21427291"."AUTHOR_AUTOINCREMENT" 
BEFORE INSERT ON author
FOR EACH ROW
BEGIN
IF :new.ID IS NULL THEN 
SELECT authorcount.NEXTVAL 
INTO :new.ID
FROM dual;
END IF;
END;
/
ALTER TRIGGER "B21427291"."AUTHOR_AUTOINCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CARICATURIST_AUTOINCREMENT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "B21427291"."CARICATURIST_AUTOINCREMENT" 
BEFORE INSERT ON caricaturist
FOR EACH ROW
BEGIN
IF :new.ID IS NULL THEN 
SELECT caricaturistcount.NEXTVAL 
INTO :new.ID
FROM dual;
END IF;
END;
/
ALTER TRIGGER "B21427291"."CARICATURIST_AUTOINCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ITEM_AUTOINCREMENT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "B21427291"."ITEM_AUTOINCREMENT" 
BEFORE INSERT ON ITEM
FOR EACH ROW
BEGIN
IF :new.ID IS NULL THEN 
SELECT itemcount.NEXTVAL 
INTO :new.ID
FROM dual;
END IF;
END;
/
ALTER TRIGGER "B21427291"."ITEM_AUTOINCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PHOTOGRAPHER_AUTOINCREMENT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "B21427291"."PHOTOGRAPHER_AUTOINCREMENT" 
BEFORE INSERT ON photographer
FOR EACH ROW
BEGIN
IF :new.ID IS NULL THEN 
SELECT photographercount.NEXTVAL 
INTO :new.ID
FROM dual;
END IF;
END;
/
ALTER TRIGGER "B21427291"."PHOTOGRAPHER_AUTOINCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PUBLISHER_AUTOINCREMENT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "B21427291"."PUBLISHER_AUTOINCREMENT" 
BEFORE INSERT ON publisher
FOR EACH ROW
BEGIN 
IF :new.ID IS NULL THEN 
SELECT publishercount.NEXTVAL 
INTO :new.ID
FROM dual;
END IF;
END;
/
ALTER TRIGGER "B21427291"."PUBLISHER_AUTOINCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger UPLOADER_AUTOINCREMENT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "B21427291"."UPLOADER_AUTOINCREMENT" 
BEFORE INSERT ON uploader
FOR EACH ROW
BEGIN 
IF :new.ID IS NULL THEN 
SELECT uploadercount.NEXTVAL 
INTO :new.ID
FROM dual;
END IF;
END;
/
ALTER TRIGGER "B21427291"."UPLOADER_AUTOINCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger UPLOADITEM_AUTOINCREMENT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "B21427291"."UPLOADITEM_AUTOINCREMENT" 
BEFORE INSERT ON upload_item
FOR EACH ROW
BEGIN 
IF :new.uploadid IS NULL THEN 
SELECT uploaditemcount.NEXTVAL 
INTO :new.uploadid
FROM dual;
END IF;
END;
/
ALTER TRIGGER "B21427291"."UPLOADITEM_AUTOINCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Procedure DELETE_ADMIN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "B21427291"."DELETE_ADMIN" 
(
 inputemail IN VARCHAR2
) AS 
BEGIN
      delete from admin1 where email=inputemail;
      delete from admin2 where email=inputemail;
      delete from admin where email=inputemail;
END;

/
--------------------------------------------------------
--  DDL for Procedure DELETE_DOWNLOADHISTORY
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "B21427291"."DELETE_DOWNLOADHISTORY" 
(
  inputitemid IN int
, inputuseremail IN VARCHAR2
) AS 
BEGIN
      delete from downloadhistory where useremail=inputuseremail and itemid=inputitemid;
END;

/
--------------------------------------------------------
--  DDL for Procedure DELETE_ITEM
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "B21427291"."DELETE_ITEM" 
(
  inputid int
) AS 
BEGIN
      delete from downloadhistory where itemid=inputid;
      delete from publisher where itemid=inputid;
      delete from author where itemid=inputid;
      delete from book where id=inputid;
      delete from caricaturist where itemid=inputid;
      delete from uploader where itemid=inputid;
      delete from caricature where id=inputid;
      delete from photographer where itemid=inputid;
      delete from wallpaper where id=inputid;
      delete from item where id=inputid;
END;

/
--------------------------------------------------------
--  DDL for Procedure DELETE_UPLOADITEM
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "B21427291"."DELETE_UPLOADITEM" 
(
  inputemail IN VARCHAR2
, inputuploadid IN int
) AS 
BEGIN
      delete from upload_book where uploadid=inputuploadid;
      delete from upload_wallpaper where uploadid=inputuploadid;
      delete from upload_caricature where uploadid=inputuploadid;
      delete from ukeep where useremail=inputemail and uploadid=inputuploadid;
      delete from upload_item where uploadid=inputuploadid;
END;

/
--------------------------------------------------------
--  DDL for Procedure DELETE_USER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "B21427291"."DELETE_USER" 
(
 inputemail IN VARCHAR2
) AS 
BEGIN
      delete from user1 where email=inputemail;
      delete from user2 where email=inputemail;
      delete from users where email=inputemail;
END;

/
--------------------------------------------------------
--  DDL for Procedure INSERT_ADMIN1
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "B21427291"."INSERT_ADMIN1" 
(
  inputtc IN VARCHAR2
, inputpassword IN VARCHAR2
, inputname IN VARCHAR2
, inputsurname IN VARCHAR2
, inputphonenumber IN VARCHAR2
, inputemail IN VARCHAR2
, inputaddress IN VARCHAR2
) AS 
BEGIN
      insert into admin values(inputtc,inputpassword,inputname,inputsurname,inputphonenumber,inputemail,inputaddress,sysdate);
      insert into admin1 values(inputemail);
END;

/
--------------------------------------------------------
--  DDL for Procedure INSERT_ADMIN2
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "B21427291"."INSERT_ADMIN2" 
(
  inputtc IN VARCHAR2
, inputpassword IN VARCHAR2
, inputname IN VARCHAR2
, inputsurname IN VARCHAR2
, inputphonenumber IN VARCHAR2
, inputemail IN VARCHAR2
, inputaddress IN VARCHAR2
, inputmembershipdate IN date
) AS 
BEGIN
      insert into admin values(inputtc,inputpassword,inputname,inputsurname,inputphonenumber,inputemail,inputaddress,inputmembershipdate);
      insert into admin2 values(inputemail);
END;

/
--------------------------------------------------------
--  DDL for Procedure INSERT_BOOK
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "B21427291"."INSERT_BOOK" 
(
  inputname IN VARCHAR2
, inputsubject IN VARCHAR2
, inputreleaseyear IN int
, inputnumberofpages IN int
, inputlanguage IN VARCHAR2
, inputauthorname IN VARCHAR2
, inputauthoremail IN VARCHAR2
, inputpublishername IN VARCHAR2
, inputpublisheremail IN VARCHAR2
, inputdirectory IN VARCHAR2
) AS 
BEGIN
      BEGIN
      SAVEPOINT beforeitem;
      insert into item(name,releaseyear,uploaddate,subject,directory) values(inputname,inputreleaseyear,SYSDATE,inputsubject,inputdirectory);
      EXCEPTION WHEN DUP_VAL_ON_INDEX THEN ROLLBACK TO beforeitem;
      END;
      
      BEGIN
      insert into book values(inputnumberofpages,inputlanguage,itemcount.currval);
      EXCEPTION WHEN DUP_VAL_ON_INDEX THEN ROLLBACK TO beforeitem;
      END;
      
      BEGIN
      insert into author(itemid,name,email) values(itemcount.currval,inputauthorname,inputauthoremail);
      EXCEPTION WHEN DUP_VAL_ON_INDEX THEN ROLLBACK TO beforeitem;
      END;
      
      BEGIN
      insert into publisher(itemid,name,email) values(itemcount.currval,inputpublishername,inputpublisheremail);
      EXCEPTION WHEN DUP_VAL_ON_INDEX THEN ROLLBACK TO beforeitem;
      END;
      
      COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure INSERT_CARICATURE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "B21427291"."INSERT_CARICATURE" 
(
  inputname IN VARCHAR2
, inputsubject IN VARCHAR2
, inputreleaseyear IN int
, inputlanguage IN VARCHAR2
, inputcaricaturistname IN VARCHAR2
, inputcaricaturistemail IN VARCHAR2
, inputuploadername IN VARCHAR2
, inputuploaderemail IN VARCHAR2
, inputdirectory IN VARCHAR2
) AS 
BEGIN
      BEGIN
      SAVEPOINT beforeitem;
      insert into item(name,releaseyear,uploaddate,subject,directory) values(inputname,inputreleaseyear,SYSDATE,inputsubject,inputdirectory);
      EXCEPTION WHEN DUP_VAL_ON_INDEX THEN ROLLBACK TO beforeitem;
      END;
      
      BEGIN
      insert into caricature values(itemcount.currval,inputlanguage);
      EXCEPTION WHEN DUP_VAL_ON_INDEX THEN ROLLBACK TO beforeitem;
      END;
      
      BEGIN
      insert into caricaturist(itemid,name,email) values(itemcount.currval,inputcaricaturistname,inputcaricaturistemail);
      EXCEPTION WHEN DUP_VAL_ON_INDEX THEN ROLLBACK TO beforeitem;
      END;
      
      BEGIN
      insert into uploader(itemid,name,email) values(itemcount.currval,inputuploadername,inputuploaderemail);
      EXCEPTION WHEN DUP_VAL_ON_INDEX THEN ROLLBACK TO beforeitem;
      END;
END;

/
--------------------------------------------------------
--  DDL for Procedure INSERT_DOWNLOADHISTORY
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "B21427291"."INSERT_DOWNLOADHISTORY" 
(
  inputitemid IN int
, inputuseremail IN VARCHAR2
) AS 
BEGIN
      insert into downloadhistory values(inputuseremail,inputitemid,SYSDATE);
END;

/
--------------------------------------------------------
--  DDL for Procedure INSERT_UPLOADBOOK
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "B21427291"."INSERT_UPLOADBOOK" 
(
  inputname IN VARCHAR2
, inputsubject IN VARCHAR2
, inputreleaseyear IN INT
, inputuseremail In varchar2
, inputnumberofpages IN int
, inputlanguage IN VARCHAR2
, inputauthorname IN VARCHAR2
, inputauthoremail IN VARCHAR2
, inputpublishername IN VARCHAR2
, inputpublisheremail IN VARCHAR2
, inputitemdirectory IN VARCHAR2
) AS
BEGIN
      insert into upload_item(name,releaseyear,uploaddate,subject, useremail, itemdirectory) values(inputname,inputreleaseyear,SYSDATE,inputsubject, inputuseremail,inputitemdirectory);
      insert into upload_book values(inputnumberofpages, inputauthoremail,inputauthorname, inputpublishername, inputpublisheremail, inputlanguage,uploaditemcount.currval);
      insert into ukeep values(inputuseremail,uploaditemcount.currval,SYSDATE);
END;

/
--------------------------------------------------------
--  DDL for Procedure INSERT_UPLOADCARICATURE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "B21427291"."INSERT_UPLOADCARICATURE" 
(
  inputname IN VARCHAR2
, inputsubject IN VARCHAR2
, inputuseremail In varchar2
, inputreleaseyear IN INT
, inputlanguage IN VARCHAR2
, inputuploadername IN VARCHAR2
, inputuploaderemail IN VARCHAR2
, inputcaricaturistname IN VARCHAR2
, inputcaricaturistemail IN VARCHAR2
, inputitemdirectory IN VARCHAR2
) AS 
BEGIN
      insert into upload_item(name,releaseyear,uploaddate,subject, useremail, itemdirectory) values(inputname,inputreleaseyear,SYSDATE,inputsubject, inputuseremail, inputitemdirectory);
      insert into upload_caricature values(inputuploadername,inputuploaderemail,inputcaricaturistname, inputcaricaturistemail, inputlanguage,uploaditemcount.currval);
      insert into ukeep values(inputuseremail,uploaditemcount.currval,SYSDATE);
END;

/
--------------------------------------------------------
--  DDL for Procedure INSERT_UPLOADWALLPAPER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "B21427291"."INSERT_UPLOADWALLPAPER" 
(
  inputname IN VARCHAR2
, inputsubject IN VARCHAR2
, inputreleaseyear IN INT
, inputuseremail IN VARCHAR2
, inputphotographername IN VARCHAR2
, inputphotographeremail IN VARCHAR2
, inputitemdirectory IN VARCHAR2
) AS 
BEGIN
      insert into upload_item(name,releaseyear,uploaddate,subject, useremail, itemdirectory) values(inputname,inputreleaseyear,SYSDATE,inputsubject, inputuseremail, inputitemdirectory);
      insert into upload_wallpaper values(inputphotographername,inputphotographeremail,uploaditemcount.currval);
      insert into ukeep values(inputuseremail,uploaditemcount.currval,SYSDATE);
END;

/
--------------------------------------------------------
--  DDL for Procedure INSERT_USER1
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "B21427291"."INSERT_USER1" 
(
  inputtc IN VARCHAR2
, inputpassword IN VARCHAR2
, inputname IN VARCHAR2
, inputsurname IN VARCHAR2
, inputphonenumber IN VARCHAR2
, inputemail IN VARCHAR2
, inputaddress IN VARCHAR2
) AS 
BEGIN
      insert into users values(inputtc,inputpassword,inputname,inputsurname,inputphonenumber,inputaddress,SYSDATE,inputemail);
      insert into user1 values(inputemail);
END;

/
--------------------------------------------------------
--  DDL for Procedure INSERT_USER2
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "B21427291"."INSERT_USER2" 
(
  inputemail IN VARCHAR2
) AS 
BEGIN
      insert into superuserrequest values(inputemail);
END;

/
--------------------------------------------------------
--  DDL for Procedure INSERT_WALLPAPER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "B21427291"."INSERT_WALLPAPER" 
(
  inputname IN VARCHAR2
, inputsubject IN VARCHAR2
, inputreleaseyear IN int
, inputphotographername IN VARCHAR2
, inputphotographeremail IN VARCHAR2
, inputdirectory IN VARCHAR2
) AS 
BEGIN
      BEGIN
      SAVEPOINT beforeitem;
      insert into item(name,releaseyear,uploaddate,subject,directory) values(inputname,inputreleaseyear,SYSDATE,inputsubject,inputdirectory);
      EXCEPTION WHEN DUP_VAL_ON_INDEX THEN ROLLBACK TO beforeitem;
      END;
      
      BEGIN
      insert into wallpaper values(itemcount.currval);
      EXCEPTION WHEN DUP_VAL_ON_INDEX THEN ROLLBACK TO beforeitem;
      END;
      
      BEGIN
      insert into photographer(itemid,name,email) values(itemcount.currval,inputphotographername,inputphotographeremail);
      EXCEPTION WHEN DUP_VAL_ON_INDEX THEN ROLLBACK TO beforeitem;
      END;
END;

/
--------------------------------------------------------
--  DDL for Procedure SUPERUSERPERMISSION
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "B21427291"."SUPERUSERPERMISSION" 
(
  inputemail IN VARCHAR2
) AS 
BEGIN
      delete from user1 where email=inputemail;
      delete from superuserrequest where email=inputemail;
      insert into user2 values(SYSDATE,inputemail);
END;

/
--------------------------------------------------------
--  DDL for Procedure UPDATE_PASSWORDADMIN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "B21427291"."UPDATE_PASSWORDADMIN" 
(
 inputemail IN VARCHAR2,
 inputpassword IN VARCHAR2
) AS 
BEGIN
      update admin set password=inputpassword where email=inputemail;
END;

/
--------------------------------------------------------
--  DDL for Procedure UPDATE_PASSWORDUSER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "B21427291"."UPDATE_PASSWORDUSER" 
(
 inputemail IN VARCHAR2,
 inputpassword IN VARCHAR2
) AS 
BEGIN
      update users set password=inputpassword where email=inputemail;
END;

/
--------------------------------------------------------
--  DDL for Procedure UPDATE_PHONENUMBERADMIN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "B21427291"."UPDATE_PHONENUMBERADMIN" 
(
 inputemail IN VARCHAR2,
 inputphonenumber IN VARCHAR2
) AS 
BEGIN
      update admin set phonenumber=inputphonenumber where email=inputemail;
END;

/
--------------------------------------------------------
--  DDL for Procedure UPDATE_PHONENUMBERUSER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "B21427291"."UPDATE_PHONENUMBERUSER" 
(
 inputemail IN VARCHAR2,
 inputphonenumber IN VARCHAR2
) AS 
BEGIN
      update users set phonenumber=inputphonenumber where email=inputemail;
END;

/
--------------------------------------------------------
--  DDL for Procedure UPLOADPERMISSIONBOOK
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "B21427291"."UPLOADPERMISSIONBOOK" 
(
  inputuser2email IN VARCHAR2
, inputuploadid IN int
) IS
itemname varchar2(30);
itemsubject varchar2(30);
itemreleaseyear int;
booknumberofpages int;
bookpublishername varchar2(30);
bookpublisheremail varchar2(30);
bookauthorname varchar2(30);
bookauthoremail varchar2(30);
booklanguage varchar2(30);
itemdirectory varchar2(200);
BEGIN
    BEGIN
    SAVEPOINT beforeitem;
    select subject,name,releaseyear,itemdirectory into itemsubject,itemname,itemreleaseyear,itemdirectory from upload_item where uploadid=inputuploadid;
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN ROLLBACK TO beforeitem;
    END;
    
    BEGIN
    select numberofpages,publishername,publisheremail,authorname,authoremail,language into booknumberofpages,bookpublishername,bookpublisheremail,bookauthorname,bookauthoremail,booklanguage from upload_book where uploadid=inputuploadid;
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN ROLLBACK TO beforeitem;
    END;
    
    BEGIN
    insert_book(itemname,itemsubject,itemreleaseyear,booknumberofpages,booklanguage,bookauthorname,bookauthoremail,bookpublishername,bookpublisheremail,itemdirectory);
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN ROLLBACK TO beforeitem;
    END;
    
    BEGIN
    delete_uploaditem(inputuser2email,inputuploadid);
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN ROLLBACK TO beforeitem;
    END;
END uploadpermissionbook;

/
--------------------------------------------------------
--  DDL for Procedure UPLOADPERMISSIONCARICATURE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "B21427291"."UPLOADPERMISSIONCARICATURE" 
(
  inputuser2email IN VARCHAR2
, inputuploadid IN int
) IS
itemname varchar2(30);
itemsubject varchar2(30);
itemreleaseyear int;
caricatureuploadername varchar2(30);
caricatureuploaderemail varchar2(30);
caricaturecaricaturistname varchar2(30);
caricaturecaricaturistemail varchar2(30);
caricaturelanguage varchar2(30);
itemdirectory varchar2(200);
BEGIN
    BEGIN
    SAVEPOINT beforeitem;
    select subject,name,releaseyear,itemdirectory into itemsubject,itemname,itemreleaseyear,itemdirectory from upload_item where uploadid=inputuploadid;
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN ROLLBACK TO beforeitem;
    END;
    
    BEGIN
    select uploadername,uploaderemail,caricaturistname,caricaturistemail,language into caricatureuploadername,caricatureuploaderemail,caricaturecaricaturistname,caricaturecaricaturistemail,caricaturelanguage from upload_caricature where uploadid=inputuploadid;
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN ROLLBACK TO beforeitem;
    END;
    
    BEGIN
    insert_caricature(itemname,itemsubject,itemreleaseyear,caricaturelanguage,caricaturecaricaturistname,caricaturecaricaturistemail,caricatureuploadername,caricatureuploaderemail,itemdirectory);     
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN ROLLBACK TO beforeitem;
    END;
    
    BEGIN
    delete_uploaditem(inputuser2email,inputuploadid);
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN ROLLBACK TO beforeitem;
    END;
END uploadpermissioncaricature;

/
--------------------------------------------------------
--  DDL for Procedure UPLOADPERMISSIONWALLPAPER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "B21427291"."UPLOADPERMISSIONWALLPAPER" 
(
  inputuser2email IN VARCHAR2
, inputuploadid IN int
) IS
itemname varchar2(30);
itemsubject varchar2(30);
itemreleaseyear int;
wallpaperphotographername varchar2(30);
wallpaperphotographeremail varchar2(30);
itemdirectory varchar2(200);
BEGIN
    BEGIN
    SAVEPOINT beforeitem;
    select subject,name,releaseyear,itemdirectory into itemsubject,itemname,itemreleaseyear,itemdirectory from upload_item where uploadid=inputuploadid;
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN ROLLBACK TO beforeitem;
    END;
    
    BEGIN
    select photographername,photographeremail into wallpaperphotographername,wallpaperphotographeremail from upload_wallpaper where uploadid=inputuploadid;
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN ROLLBACK TO beforeitem;
    END;
    
    BEGIN
    insert_wallpaper(itemname,itemsubject,itemreleaseyear,wallpaperphotographername,wallpaperphotographeremail,itemdirectory);
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN ROLLBACK TO beforeitem;
    END;
    
    BEGIN
    delete_uploaditem(inputuser2email,inputuploadid);
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN ROLLBACK TO beforeitem;
    END;
END uploadpermissionwallpaper;

/
